import Head from "next/head";
import Navbar from "../components/navbar/Navbar";
import Script from "next/script";
import Footer from "../components/footer/footer";
import Header from "../components/header/header";
import Image from "next/image";
import Link from "next/link";


export default function Home( ) {
  return (
    <div>
      <Head>
        <title>Broadcast LVP</title>
        <meta name="Web del departamento de Broadcast de la LVP" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Script src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></Script>
        <Script src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></Script>

        <Navbar />
        <div className="m-28"></div>
        <div>
          <Header data="WEB BROADCAST LVP" />
        </div>
        <div className="container flex justify-center items-center gap-10 ">
          <div className="w-ful h-full overflow-hidden">
            <Image
              src="/racks.png"
              width={1800}
              height={1800}
              className="opacity-25 w-full object-cover"
              alt="fondo"
            />
          </div> 
        </div>
        <Footer />
      </main>
      
    </div>
  );
}
